test

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,50 +1,50 @@
-name: CI/CD Pipeline
+# name: CI/CD Pipeline
 
-on:
-  push:
-    branches: ["master"]
+# on:
+#   push:
+#     branches: ["master"]
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Source
-        uses: actions/checkout@v3
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout Source
+#         uses: actions/checkout@v3
 
-      - name: Login to Docker Hub
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+#       - name: Login to Docker Hub
+#         env:
+#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+#         run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 
-      - name: Build Docker Image
-        run: docker build -t jpswann0208/jpswann-app .
+#       - name: Build Docker Image
+#         run: docker build -t jpswann0208/jpswann-app .
 
-      - name: Publish Image To Docker Hub
-        run: docker push jpswann0208/jpswann-app:latest
+#       - name: Publish Image To Docker Hub
+#         run: docker push jpswann0208/jpswann-app:latest
 
-  deploy:
-    needs: build
-    runs-on: self-hosted
-    steps:
-      - name: Create .env File
-        run: |
-          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
-          echo "GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}" >> .env
-          echo "GH_SECRET=${{ secrets.GH_SECRET }}" >> .env
-          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
+#   deploy:
+#     needs: build
+#     runs-on: self-hosted
+#     steps:
+#       - name: Create .env File
+#         run: |
+#           echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
+#           echo "GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}" >> .env
+#           echo "GH_SECRET=${{ secrets.GH_SECRET }}" >> .env
+#           echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
 
-      - name: Pull Docker Image
-        run: sudo docker pull jpswann0208/jpswann-app:latest
+#       - name: Pull Docker Image
+#         run: sudo docker pull jpswann0208/jpswann-app:latest
 
-      - name: Stop and Remove Old Container
-        run: |
-          sudo docker stop jpswann-app-container || true
-          sudo docker rm jpswann-app-container || true
+#       - name: Stop and Remove Old Container
+#         run: |
+#           sudo docker stop jpswann-app-container || true
+#           sudo docker rm jpswann-app-container || true
 
-      - name: Run Docker Container
-        run: sudo docker run --env-file .env -d -p 3000:80 --name jpswann-app-container jpswann0208/jpswann-app
+#       - name: Run Docker Container
+#         run: sudo docker run --env-file .env -d -p 3000:80 --name jpswann-app-container jpswann0208/jpswann-app
 
-      - name: Clean up unused Docker resources
-        run: |
-          sudo docker system prune -f
+#       - name: Clean up unused Docker resources
+#         run: |
+#           sudo docker system prune -f
